accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/follows/', views.follows, name='follows'),
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.main, name='main'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/likes/', views.likes, name='likes'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),
    path('<int:id>/likes-async/', views.likes_async, name='likes_async'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField

# Create your models here.
class User(AbstractUser):
    profile_image = ResizedImageField(
        size =[500, 500],
        crop=['middle', 'center'],
        upload_to='profile'
    )


    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.

class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='image/%Y/%m')
    image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='image/%Y/%m'
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'profile_image',)




class CustomAuthenticationForm(AuthenticationForm):
    pass

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        exclude = ('user', 'like_users',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User
# Create your views here.

def signup(request):
    if request.method=='POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    
    context = {
        'form' : form,
    }

    return render(request, 'accounts_form.html', context)

def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')

    else:
        form = CustomAuthenticationForm()
    
    context = {
        'form' : form,
    }
    
    return render(request, 'accounts_form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

def profile(request, username):
    user_info = User.objects.get(username=username)

    context = {
        'user_info' : user_info,
    }

    return render(request, 'profile.html', context)

def follows(request, username):
    me = request.user
    you = User.objects.get(username=username)

    #이미 팔로잉이 되어있는 경우
    if you in me.followings.all():
        me.followings.remove(you)
    # 아직 팔로잉이 안된 경우
    else:
        me.followings.add(you)

    return redirect('accounts:profile', username=username)

insta/views.py
from django.shortcuts import redirect

def main(request):
    return redirect('posts:index')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-id')

    context = {
        'posts' : posts,
    }

    return render(request, 'index.html', context)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)

            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form' : form,
    }

    return render(request, 'form.html', context)

def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('posts:index')

@login_required
def update(request, id):
    post = Post.objects.get(id=id)

    if request.user != post.user:
        return redirect('posts:detail', id=id)

    if request.method == 'POST':
        form = PostForm(request.POST,instance=post)
        if form.is_valid():
            post = form.save(commit=False)

            post.user = request.user
            post.save()

            return redirect('posts:detail', id=post.id)
    else:
        form = PostForm(instance=post)
    
    context = {
        'form' : form,
    }

    return render(request, 'form.html', context)


@login_required
def likes(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    # 이미 좋아요를 누른 경우
    # if post in user.like_posts.all():
    # 아래 위 코드는 아래와 같은 이유로 같은 코드다.
    if user in post.like_users.all():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    # 아래 위는 user 정보와 post정보를 동시에 저장한다는 점에서 같은 코드다.(양방향성)
    # user.like_posts.add(post)

    return redirect('posts:index')

from django.http import JsonResponse
def likes_async(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False
    else:
        post.like_users.add(user)
        status = True

    context = {
        'status' : status,
        'count' : len(post.like_users.all()),
    }

    return JsonResponse(context)


@login_required
def comment_create(request, post_id):
    form = CommentForm(request.POST)
    # article= Article.objects.get(id=id)

    if form.is_valid():
        comment = form.save(commit=False)
 
        comment.user_id = request.user.id
        comment.post_id = post_id
        comment.save()

        return redirect('posts:detail', id=post_id)

def detail(request, id):
    post = Post.objects.get(id=id)
    form = CommentForm

    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'detail.html', context)

@login_required
def comment_delete(request, post_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    
    if request.user == comment.user:
        comment.delete()
    
    return redirect('posts:detail', id=post_id)

accounts/templates/accounts_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}

{% block body %}
    <div class="row mt-3">
        <div class="col-4">
            {% if user_info.profile_image %}
            <img src="{{ user_info.profile_image.url }}" alt="" class="rounded-circle img-fluid">
            {% else %}
            <img src="/media/profile/default.jpeg" alt="" class="rounded-circle img-fluid">
            {% endif %}
        </div>
        <div class="col-8">
            <div class="row">
                <div class="col-3">
                    {{user_info}}
                </div>
                {% if user != user_info %}
                <div class="col-4">
                    {% if user in user_info.followers.all %}
                    <a href="{% url 'accounts:follows' username=user_info %}" class="btn btn-primary">팔로잉</a>
                    {% else %}
                    <a href="{% url 'accounts:follows' username=user_info %}" class="btn btn-secondary">팔로우</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>

            <div class="row">
                <div class="col">게시물{{user_info.post_set.all|length}}개</div> 
                <div class="col">팔로워{{user_info.followers.all|length}}</div>
                <div class="col">팔로우{{user_info.followings.all|length}}</div>
            </div>
        </div>
    </div>

    <div class="row row-cols-3">
        {% for post in user_info.post_set.all %}
        <div class="col">
                <div class="card">
                    <img src="{{ post.image.url }}" alt="">
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/_card.html
<div class="card my-5 col-12 col-md-6">
    <div class="card-header">
        {% if post.user.profile_image %}
            <img src="{{ post.user.profile_image.url }}" alt="" class="rounded-circle" width="30px">
        {% else %}
            <img src="/media/profile/default.jpeg" alt="" class="rounded-circle" width="30px">
        {% endif %}
        <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{post.user}}</a>
    </div>
    <img src="{{ post.image.url }}" alt="">
    <div class="card-body">
        
            {% if user in post.like_users.all %}
                <i class="bi bi-heart-fill heart" style="color:red" data-post-id="{{post.id}}">{{ post.like_users.all|length }}</i>
            {% else %}
                <i class="bi bi-heart heart" data-post-id="{{post.id}}">{{ post.like_users.all|length }}</i>
            {% endif%}
         명이 종아합니다.
        <p class="card-text">{{ post.content }}</p>
        <a href="{% url 'posts:detail' id=post.id %}" class="btn btn-dark">게시글보기</a> <br><hr>
        {% if user == post.user %}
        <a href="{% url 'posts:delete' id=post.id %}" class="btn btn-danger btn-sm">게시물삭제</a>
        <a href="{% url 'posts:update' id=post.id %}" class="btn btn-warning btn-sm">업데이트</a>
        {% endif %}

    </div>
</div>

posts/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block body %}
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{ post.image.url }}" class="img-fluid rounded-start" alt="">
        </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">
                {% if post.user.profile_image %}
                    <img src="{{ post.user.profile_image.url }}" alt="" class="rounded-circle" width="30px">
                {% else %}
                    <img src="/media/profile/default.jpeg" alt="" class="rounded-circle" width="30px">
                {% endif %}
                    <a href="{% url 'accounts:profile' username=post.user %}">{{post.user}}</a>
            </h5>
            <p class="card-text">{{ post.content }}</p>
            <p class="card-text"><small class="text-body-secondary"></small></p>

                {% if user in post.like_users.all %}
                <i class="bi bi-heart-fill heart" style="color:red" data-post-id="{{post.id}}">{{ post.like_users.all|length }}</i>
                {% else %}
                    <i class="bi bi-heart heart" data-post-id="{{post.id}}">{{ post.like_users.all|length }}</i>
                {% endif%}
             명이 종아합니다.
            {% if user == post.user %}
            <a href="{% url 'posts:delete' id=post.id %}" class="btn btn-danger btn-sm">게시물삭제</a>
            <a href="{% url 'posts:update' id=post.id %}" class="btn btn-warning btn-sm">업데이트</a>
            {% endif %}
            <hr>
            <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-10">
                        {% bootstrap_form form show_label=False %}
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary">
                    </div>
                </div>
            </form>
            <hr>
            {% for comment in post.comment_set.all %}
            <div class="alert alert-light">
                <p>{{comment.user}} : {{comment.content}}</p>
                {% if user == comment.user %}
                <a href="{% url 'posts:comment_delete' post_id=post.id  comment_id=comment.id %}" class="btn btn-danger btn-sm">Delete</a>
                <hr>
                {% endif %}
            </div>
            {% endfor %}

        </div>
      </div>
    </div>
  </div>
  <script>
    let likeButtons = document.querySelectorAll("i.heart")
    // console.log(likeButtons)

    likeButtons.forEach((likeButton)=>{
        // console.log(likeButton)
        likeButton.addEventListener("click", (event)=>{
            // console.log(event.target)
            let postId = event.target.dataset.postId

            likeRequest(event.target, postId)

        })
    })

    let likeRequest = async (button, postId) => {
        // console.log(button, postId)
        let likeURL = `/posts/${postId}/likes-async/`
        // console.log(likeURL)
        let response = await fetch(likeURL)
        let result = await response.json()

        // console.log(result)

        //좋아요가 눌린 경우
        if(result.status){
            button.classList.remove('bi-heart')
            button.classList.add('bi-heart-fill')
            button.style.color = 'red'
            button.innerHTML = result.count
        } 
        // 좋아요가 취소된 경우
        else {
            button.classList.remove('bi-heart-fill')
            button.classList.add('bi-heart')
            button.style.color = 'black'
            button.innerHTML = result.count
        }
    }
    
</script>
{% endblock %}

posts/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
    {% for post in posts %}
        {% include '_card.html' %}
    {% endfor %}
</div>

<script>
    let likeButtons = document.querySelectorAll("i.heart")
    // console.log(likeButtons)

    likeButtons.forEach((likeButton)=>{
        // console.log(likeButton)
        likeButton.addEventListener("click", (event)=>{
            // console.log(event.target)
            let postId = event.target.dataset.postId

            likeRequest(event.target, postId)

        })
    })

    let likeRequest = async (button, postId) => {
        // console.log(button, postId)
        let likeURL = `/posts/${postId}/likes-async/`
        // console.log(likeURL)
        let response = await fetch(likeURL)
        let result = await response.json()

        // console.log(result)

        //좋아요가 눌린 경우
        if(result.status){
            button.classList.remove('bi-heart')
            button.classList.add('bi-heart-fill')
            button.style.color = 'red'
            button.innerHTML = result.count
        } 
        // 좋아요가 취소된 경우
        else {
            button.classList.remove('bi-heart-fill')
            button.classList.add('bi-heart')
            button.style.color = 'black'
            button.innerHTML = result.count
        }
    }
    
</script>

{% endblock %}

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <i class="bi bi-instagram"></i> 𝓘𝓷𝓼𝓽𝓪𝓰𝓻𝓪𝓶
    </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'posts:create' %}">Create</a>
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            <a class="nav-link disabled" aria-disabled="true">{{user}}</a>
            {% else %}
            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
        </div>
      </div>
    </div>
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <style>
        body {
            background-color: gray; 
        }
    </style>
</head>
<body style="background-color:white">
    {% include '_nav.html' %}
    <div class="container">
        {% block body %}
        
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>